"""empty message

Revision ID: 15b552c99b42
Revises: d5357a178c6a
Create Date: 2020-12-17 23:56:40.063279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b552c99b42'
down_revision = 'd5357a178c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'zoom_meetings', ['meeting_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoom_meetings', type_='unique')
    # ### end Alembic commands ###
