"""empty message

Revision ID: 189faa4b3819
Revises: 71a47016e891
Create Date: 2020-12-10 20:12:28.350459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189faa4b3819'
down_revision = '71a47016e891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('sender_name', sa.String(length=50), nullable=False),
    sa.Column('sender_email', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('updated_at >= created_at'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail')
    # ### end Alembic commands ###
