"""empty message

Revision ID: 23eb3b606f87
Revises: 8539c66654fd
Create Date: 2021-01-12 16:34:05.899062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23eb3b606f87'
down_revision = '8539c66654fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_slack_channel_members_user_id'), 'slack_channel_members', ['user_id'], unique=False)
    op.drop_index('user_id', table_name='slack_channel_members')
    op.alter_column('slack_channels', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('slack_messages', sa.Column('file_deleted', sa.Integer(), nullable=True))
    op.add_column('slack_messages', sa.Column('file_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_messages', 'file_name')
    op.drop_column('slack_messages', 'file_deleted')
    op.alter_column('slack_channels', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index('user_id', 'slack_channel_members', ['user_id', 'channel_id'], unique=True)
    op.drop_index(op.f('ix_slack_channel_members_user_id'), table_name='slack_channel_members')
    # ### end Alembic commands ###
