"""empty message

Revision ID: 46d46073556b
Revises: 72acc444942e
Create Date: 2020-12-21 01:17:38.347673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d46073556b'
down_revision = '72acc444942e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail', sa.Column('subject', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail', 'subject')
    # ### end Alembic commands ###
