"""empty message

Revision ID: 48ead5f04096
Revises: b7ae92f554a8
Create Date: 2021-01-13 22:18:38.892455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48ead5f04096'
down_revision = 'b7ae92f554a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zoom_meetings', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('meeting_id', table_name='zoom_meetings')
    op.create_unique_constraint(None, 'zoom_meetings', ['meeting_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoom_meetings', type_='unique')
    op.create_index('meeting_id', 'zoom_meetings', ['meeting_id'], unique=True)
    op.alter_column('zoom_meetings', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
