"""empty message

Revision ID: 56d873f464d4
Revises: 8539c66654fd
Create Date: 2021-01-12 16:52:49.876512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56d873f464d4'
down_revision = '8539c66654fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_channels', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('slack_messages', sa.Column('file_deleted', sa.Integer(), nullable=True))
    op.add_column('slack_messages', sa.Column('file_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_messages', 'file_name')
    op.drop_column('slack_messages', 'file_deleted')
    op.alter_column('slack_channels', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
