"""empty message

Revision ID: 578575648a3b
Revises: bd1b6d81f7be
Create Date: 2020-12-20 23:26:09.766858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578575648a3b'
down_revision = 'bd1b6d81f7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('sort_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'sort_date')
    # ### end Alembic commands ###
