"""empty message

Revision ID: 6755f793ae88
Revises: 9683885d1b6e
Create Date: 2020-12-16 21:31:23.701540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6755f793ae88'
down_revision = '9683885d1b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_information_name'), 'information', ['name'], unique=False)
    op.drop_index('ix_users_name', table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_index(op.f('ix_information_name'), table_name='information')
    op.drop_column('information', 'name')
    # ### end Alembic commands ###
