"""empty message

Revision ID: 961a5c956e34
Revises: 99d1957b9eae
Create Date: 2020-09-20 21:19:29.699667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961a5c956e34'
down_revision = '99d1957b9eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('event_time', sa.Integer(), nullable=False),
    sa.Column('message_time', sa.Float(precision=10), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('update_at >= create_at'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_channel'), 'actions', ['channel'], unique=False)
    op.create_index(op.f('ix_actions_event_type'), 'actions', ['event_type'], unique=False)
    op.create_index(op.f('ix_actions_team_id'), 'actions', ['team_id'], unique=False)
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.add_column('employees', sa.Column('slack_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_employees_slack_id'), 'employees', ['slack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_slack_id'), table_name='employees')
    op.drop_column('employees', 'slack_id')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_team_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_event_type'), table_name='actions')
    op.drop_index(op.f('ix_actions_channel'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
