"""empty message

Revision ID: a82eac4e419c
Revises: 6755f793ae88
Create Date: 2020-12-16 22:31:20.662049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82eac4e419c'
down_revision = '6755f793ae88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_gmail', table_name='users')
    op.create_index(op.f('ix_users_gmail'), 'users', ['gmail'], unique=True)
    op.drop_index('ix_users_slack_id', table_name='users')
    op.create_index(op.f('ix_users_slack_id'), 'users', ['slack_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slack_id'), table_name='users')
    op.create_index('ix_users_slack_id', 'users', ['slack_id'], unique=False)
    op.drop_index(op.f('ix_users_gmail'), table_name='users')
    op.create_index('ix_users_gmail', 'users', ['gmail'], unique=False)
    # ### end Alembic commands ###
