"""empty message

Revision ID: b8ffabb44eee
Revises: 15b552c99b42
Create Date: 2020-12-18 17:19:09.469893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8ffabb44eee'
down_revision = '15b552c99b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('zoom_user_id', sa.String(length=50), nullable=False),
    sa.Column('zoom_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('updated_at >= created_at'),
    sa.ForeignKeyConstraint(['meeting_id'], ['zoom_meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id'),
    sa.UniqueConstraint('zoom_user_id', 'meeting_id')
    )
    op.drop_table('zoom_messages')
    op.drop_table('zoom_recordings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_recordings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start', mysql.DATETIME(), nullable=False),
    sa.Column('end', mysql.DATETIME(), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('(`updated_at` >= `created_at`)', name='zoom_recordings_chk_1'),
    sa.ForeignKeyConstraint(['meeting_id'], ['zoom_meetings.id'], name='zoom_recordings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('zoom_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('(`updated_at` >= `created_at`)', name='zoom_messages_chk_1'),
    sa.ForeignKeyConstraint(['meeting_id'], ['zoom_meetings.id'], name='zoom_messages_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='zoom_messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('zoom_participants')
    # ### end Alembic commands ###
