"""empty message

Revision ID: ba7ca04ac897
Revises: 00b4bb16bdae
Create Date: 2021-01-13 00:08:11.544193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba7ca04ac897'
down_revision = '00b4bb16bdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('creator_id', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
